openapi: 3.1.0
info:
  title: Submit Community Event
  version: 1.0.0
  description: Submit event details from a flyer image to a webhook if the event isn't already in Airtable.
servers:
  - url: https://hooks.zapier.com/hooks/catch/2066959/2ep8bmf/
paths:
  /:
    post:
      operationId: submitEventFromImage
      summary: Submit an event found on a flyer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_name:
                  type: string
                date_time:
                  type: string
                location:
                  type: string
                link:
                  type: string
                tags:
                  type: string
                source:
                  type: string
              required:
                - event_name
                - source
      responses:
        "200":
          description: Event submitted successfully

